export const defaultArr = {
  cells: [
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "1",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "2",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "3",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "4",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "5",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "6",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "7",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "8",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "9",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "10",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "11",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "12",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "13",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "14",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "15",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "16",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "17",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "18",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "19",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "20",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "21",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "22",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "23",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "24",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "25",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "26",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "27",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "28",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "29",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "30",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "31",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "32",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "33",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "34",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "35",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "36",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "37",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "38",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "39",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "40",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "41",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "42",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "43",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "44",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "45",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "46",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "47",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "48",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "49",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "50",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "51",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "52",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "53",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "54",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "55",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "56",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "57",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "58",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "59",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "60",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "61",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "62",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "63",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "64",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "65",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "66",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "67",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "68",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "69",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "70",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "71",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "72",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "73",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "74",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "75",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "76",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "77",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "78",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "79",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "80",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "81",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "82",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "83",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "84",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "85",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "86",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "87",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "88",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "89",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "90",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "91",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "92",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "93",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "94",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "95",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "96",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "97",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "98",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "99",
    },
    {
      empty: true,
      filled: false,
      wounded: false,
      killed: false,
      checked: false,
      id: "100",
    },
  ],
};
