const arr = Array.from({ length: 100 }, (_, i) => ({
  id: i + 1,
  empty: true,
  wounded: false,
  killed: false,
  checked: false,
}));

export const defaultArr = {
  cells: arr,
};

// export const defaultArr = {
//   cells: [
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "1",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "2",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "3",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "4",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "5",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "6",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "7",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "8",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "9",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "10",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "11",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "12",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "13",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "14",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "15",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "16",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "17",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "18",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "19",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "20",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "21",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "22",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "23",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "24",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "25",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "26",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "27",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "28",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "29",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "30",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "31",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "32",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "33",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "34",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "35",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "36",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "37",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "38",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "39",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "40",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "41",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "42",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "43",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "44",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "45",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "46",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "47",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "48",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "49",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "50",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "51",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "52",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "53",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "54",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "55",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "56",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "57",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "58",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "59",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "60",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "61",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "62",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "63",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "64",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "65",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "66",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "67",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "68",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "69",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "70",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "71",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "72",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "73",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "74",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "75",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "76",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "77",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "78",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "79",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "80",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "81",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "82",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "83",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "84",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "85",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "86",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "87",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "88",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "89",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "90",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "91",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "92",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "93",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "94",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "95",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "96",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "97",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "98",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "99",
//     },
//     {
//       empty: true,
//       wounded: false,
//       killed: false,
//       checked: false,
//       id: "100",
//     },
//   ],
// };
